In [2]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 24.3.1 -> 25.1.1
[notice] To update, run: C:\Python312\python.exe -m pip install --upgrade pip


In [3]:
# create array using numpy
import numpy as np
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
arr1.shape

[1 2 3 4 5]
<class 'numpy.ndarray'>


(5,)

In [4]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [5]:
# 2D array
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
arr2.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [6]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [7]:
# All ones
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
# All zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
# Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
# Attributes of numpy array
arr = np.array([[1,2,3],[4,5,6]])
print("Array : \n",arr)
print("Shape :",arr.shape)
print("Number of dimensions :",arr.ndim)
print("Number of elements (size) :", arr.size)
print("data type : ",arr.dtype)
print("Item size (in bytes) :",arr.itemsize)


Array : 
 [[1 2 3]
 [4 5 6]]
Shape : (2, 3)
Number of dimensions : 2
Number of elements (size) : 6
data type :  int32
Item size (in bytes) : 4


In [11]:
# Numpy vectorised operation 
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

# Element wise addition 
print("addition : ", arr1+arr2)

# Element wise subtraction 
print("subtraction : ", arr1-arr2)

# Element wise multiplication 
print("multiplication : ", arr1*arr2)

# Element wise division 
print("division : ", arr1/arr2)


addition :  [11 22 33 44 55]
subtraction :  [ -9 -18 -27 -36 -45]
multiplication :  [ 10  40  90 160 250]
division :  [0.1 0.1 0.1 0.1 0.1]


In [12]:
# Universal Functions
arr = np.array([2,3,4,5,6])

# square root
print(np.sqrt(arr))

# Exponential
print(np.exp(arr))

# Sin
print(np.sin(arr))

# Log

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]


In [83]:
# Array slicing and Indexing 
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("array : \n",arr)

array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [74]:
# Single element
arr[0,3]

4

In [44]:
# First 2 rows
arr[0:2,:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [51]:
# First 2 columns
arr[:,0:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [ ]:
# Middle block
arr[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [52]:
# Modify array elements
arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [92]:
# Diagonal of an array
arr1 = np.array([[11, 12, 13, 14],
                [21, 22, 23, 24],
                [31, 32, 33, 34],
                [41, 42, 43, 44]])

# Main diagonal (i == j)
for i in range(4):
    print(arr1[i][i],end = " ")



11 22 33 44 

In [72]:
# More efficient way
diagonal = [arr1[i][i] for i in range(4)]
print(diagonal)


[11, 22, 33, 44]


In [ ]:
# Diagonal of an array using np.diagonal()
np.diagonal(arr1)

array([11, 22, 33, 44])

In [82]:
# Making all diagonal values 0
np.fill_diagonal(arr1, 0)
print(arr1)

[[ 0 12 13 14]
 [21  0 23 24]
 [31 32  0 34]
 [41 42 43  0]]
