Indexing

In [3]:
import torch
import numpy as np
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [17]:
# Indexing
x[0],x[0,0],x[0,0,0]

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3]),
 tensor(1))

In [19]:
x[0,2,2]

tensor(9)

In [20]:
# Can use : to target all the values of the target dimension
x[:,0]

tensor([[1, 2, 3]])

In [25]:
x[0,:,2]

tensor([3, 6, 9])

Pytorch tensor and numpy 

In [28]:
# Numpy array to tensor
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [30]:
array.dtype

dtype('float64')

In [31]:
torch.arange(1.0,8.0).dtype

torch.float32

In [33]:
# Tensor to numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

Reproducibility (random seed)

In [36]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8890, 0.6162, 0.7266, 0.3863],
        [0.4876, 0.2463, 0.1274, 0.1929],
        [0.3022, 0.5475, 0.8364, 0.4869]])
tensor([[0.3041, 0.6004, 0.5173, 0.1223],
        [0.7257, 0.3199, 0.5885, 0.6356],
        [0.0750, 0.3946, 0.0572, 0.5758]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [42]:
# Random reproducible tensors
RANDOM_SEED = 7

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.5349, 0.1988, 0.6592, 0.6569],
        [0.2328, 0.4251, 0.2071, 0.6297],
        [0.3653, 0.8513, 0.8549, 0.5509]])
tensor([[0.5349, 0.1988, 0.6592, 0.6569],
        [0.2328, 0.4251, 0.2071, 0.6297],
        [0.3653, 0.8513, 0.8549, 0.5509]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [44]:
torch.cuda.is_available()

False