### Matrix multiplication 

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cpu


In [5]:
# Element wise 
tensor = torch.tensor([1,2,3])
print(tensor, '*', tensor)
print(f"Equals : ", {tensor * tensor})

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals :  {tensor([1, 4, 9])}


In [ ]:
# Matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
# "@" --> Matrix multiplication
tensor @ tensor


tensor(14)

Two main rules for matrix multiplication

1. The **inner dimnesions** must match : 
* (3,2) @ (3,2) ---> won't work
* (3,2) @ (2,3) ---> will work
* (2,3) @ (3,2) ---> will work

2. The resulting matrix has the shape of the **outer dimensions**
* (2,3) @ (3,2) ---> (2,2)
* (3,2) @ (2,3) ---> (3,3)


In [14]:
mul = torch.matmul(torch.rand(2,5), torch.rand(5,2))
mul

tensor([[0.3616, 0.7436],
        [0.4585, 1.1968]])

In [15]:
mul.shape

torch.Size([2, 2])

## Transpose
To fix the tensor shape issue, we can multiply the shape of one of our tensors using a **transpose**. 

In [ ]:
tensor_A = torch.tensor([[1,2],[3,4],[5,6]])
tensor_B = torch.tensor([[7,10],[8,11],[9,12]])

In [20]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [21]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
torch.matmul(tensor_A,tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [25]:
torch.matmul(tensor_A,tensor_B.T).shape

torch.Size([3, 3])

Finding the min,max,mean,sum(Tensor aggregation)

In [32]:
# Create a tensor
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [38]:
# Sum
torch.sum(x),x.sum()

(tensor(450), tensor(450))

In [33]:
# Find the max
torch.min(x), x.min()

(tensor(0), tensor(0))

In [34]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [37]:
# Mean 
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()
# NOTE - the torch.mean() function requires a tensor of float32 datatype to work

(tensor(45.), tensor(45.))

Finding the positional min and max

In [ ]:
# Find the position in tensor that has the minimum value with argmin() --> returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [41]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

Reshaping, stacking, squeezing, unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Shares the same memory as the original tensor, shows the same tensor for a different perspective
* Stacking - Combining multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all '1' dimensions from a tensor 
* Unsqueeze - add a '1' dimension to a target tensor 
* Permute - Returns a view of the input with dimensions permuted (swapped) in a certain way

In [43]:
x = torch.arange(1.,10.)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [61]:
# Add extra dimension 
x_reshaped = x.reshape(1,9)
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# Change the view
z = x.view(1,9)
z, z.shape 

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [53]:
# Changing z changes x as they share the same memory as the original    
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [56]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x],dim = 0)
x_stacked


tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [62]:
# torch.squeeze() - removes all single dimension from a target tensor
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [63]:
x_reshaped.shape

torch.Size([1, 9])

In [64]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [67]:
x_reshaped.squeeze().shape

torch.Size([9])

In [78]:
print(f"Previous tensor : {x_reshaped}")
print(f"Previous tensor shape : {x_reshaped.shape}")
# Removes extra dimension from x_shaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor : {x_squeezed}")
print(f"New tensor shape : {x_squeezed.shape}")


Previous tensor : tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous tensor shape : torch.Size([1, 9])

New tensor : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New tensor shape : torch.Size([9])


In [81]:
# torch.unsqueeze() - adds a single dimension from a target tensor at a specific dimension
print(f"Previous target : {x_squeezed}")
print(f"Previous shape : {x_squeezed.shape}")

# Adds an extra dimension with unsqueezed 
x_unsqueesed = x_squeezed.unsqueeze(dim = 0)
print(f"\nNew tensor : [x.unsqueezed]")
print(f"New tensor shape : [x.unsqueezed.shape]")

Previous target : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape : torch.Size([9])

New tensor : [x.unsqueezed]
New tensor shape : [x.unsqueezed.shape]


In [ ]:
# torch.permute --> rearranges the dimensions of a target tensor in a specified order 
x_original = torch.rand(size = (224,224,3)) #[height, width, color_channels]

# permute the original tensor to rearrange the axis (or dimension) order
x_permuted = x_original.permute(2,0,1)  # Shifts axis 0->1, 1->2, 2->0

print(f"Pervious shape : {x_original.shape}")
print(f"New shape : {x_permuted.shape}") #[color_channels, height, width]

Pervious shape : torch.Size([224, 224, 3])
New shape : torch.Size([3, 224, 224])
